/**
 * Curated FRED series list for Daily Chart Crime.
 * Auto-generated from strict_curated.json by maintenance tooling.
 * 351 series total.
 *
 * To regenerate after running tools/compute_correlations.py:
 *   python3 -c "
 *   import json
 *   with open('strict_curated.json') as f: series = json.load(f)
 *   lines = ['export const CURATED_SERIES = [']
 *   for s in series:
 *     t = s['title'].replace('\"', '\\\\\"')
 *     lines.append(f'  {{ id: \"{s[\"id\"]}\", title: \"{t}\" }},')
 *   lines.append('];')
 *   open('src/curated.js', 'w').write('\n'.join(lines) + '\n')
 *   "
 */
export const CURATED_SERIES = [
  { id: 'BAMLHE00EHYIOAS', title: 'ICE BofA Euro High Yield Index Option-Adjusted Spread' },
  { id: 'BAMLH0A3HYC', title: 'ICE BofA CCC & Lower US High Yield Index Option-Adjusted Spread' },
  { id: 'BAMLH0A3HYCSYTW', title: 'ICE BofA CCC & Lower US High Yield Index Semi-Annual Yield to Worst' },
  { id: 'BAMLH0A3HYCEY', title: 'ICE BofA CCC & Lower US High Yield Index Effective Yield' },
  { id: 'BAMLH0A1HYBB', title: 'ICE BofA BB US High Yield Index Option-Adjusted Spread' },
  { id: 'BAMLH0A0HYM2', title: 'ICE BofA US High Yield Index Option-Adjusted Spread' },
  { id: 'KCPRU', title: 'Kansas City Fed\'s Measure of Policy Rate Uncertainty (KCPRU)' },
  { id: 'BAMLH0A0HYM2SYTW', title: 'ICE BofA US High Yield Index Semi-Annual Yield to Worst' },
  { id: 'BAMLH0A2HYB', title: 'ICE BofA Single-B US High Yield Index Option-Adjusted Spread' },
  { id: 'BAMLC0A1CAAA', title: 'ICE BofA AAA US Corporate Index Option-Adjusted Spread' },
  { id: 'BAMLEM2BRRBBBCRPIOAS', title: 'ICE BofA BBB Emerging Markets Corporate Plus Index Option-Adjusted Spread' },
  { id: 'AAA10Y', title: 'Moody\'s Seasoned Aaa Corporate Bond Yield Relative to Yield on 10-Year Treasury Constant Maturity' },
  { id: 'BAMLEM2RBBBLCRPIUSOAS', title: 'ICE BofA BBB US Emerging Markets Liquid Corporate Plus Index Option-Adjusted Spread' },
  { id: 'BAMLH0A2HYBSYTW', title: 'ICE BofA Single-B US High Yield Index Semi-Annual Yield to Worst' },
  { id: 'BAMLC4A0C710Y', title: 'ICE BofA 7-10 Year US Corporate Index Option-Adjusted Spread' },
  { id: 'T10Y3M', title: '10-Year Treasury Constant Maturity Minus 3-Month Treasury Constant Maturity' },
  { id: 'BAMLEMIBHGCRPIOAS', title: 'ICE BofA High Grade Emerging Markets Corporate Plus Index Option-Adjusted Spread' },
  { id: 'OBFR1', title: 'Overnight Bank Funding Rate: 1st Percentile' },
  { id: 'BAMLEM1RAAA2ALCRPIUSSYTW', title: 'ICE BofA AAA-A US Emerging Markets Liquid Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'BAMLEMXOCOLCRPIUSOAS', title: 'ICE BofA Crossover US Emerging Markets Liquid Corporate Plus Index Option-Adjusted Spread' },
  { id: 'RPONTSYD', title: 'Overnight Repurchase Agreements: Treasury Securities Purchased by the Federal Reserve in the Temporary Open Market Operations' },
  { id: 'RPONTSYSAD', title: 'Overnight Repurchase Agreements: Amount of Treasury Securities Submitted' },
  { id: 'RPTSYD', title: 'Repurchase Agreements: Treasury Securities Purchased by the Federal Reserve in the Temporary Open Market Operations' },
  { id: 'RPTSYSAD', title: 'Total Repurchase Agreements: Amount of Treasury Securities Submitted' },
  { id: 'BAMLEM5BCOCRPIOAS', title: 'ICE BofA Crossover Emerging Markets Corporate Plus Index Option-Adjusted Spread' },
  { id: 'NONFIN59A2P2AMT', title: 'Total Value of Issues, with a Maturity Between 5 and 9 Days, Used in Calculating the A2/P2 Nonfinancial Commercial Paper Rates' },
  { id: 'BAMLEMALLCRPIASIAUSOAS', title: 'ICE BofA Asia US Emerging Markets Liquid Corporate Plus Index Option-Adjusted Spread' },
  { id: 'BAMLC3A0C57Y', title: 'ICE BofA 5-7 Year US Corporate Index Option-Adjusted Spread' },
  { id: 'NONFIN59A2P2VOL', title: 'Number of Issues, with a Maturity Between 5 and 9 Days, Used in Calculating the A2/P2 Nonfinancial Commercial Paper Rates' },
  { id: 'DGS3', title: 'Market Yield on U.S. Treasury Securities at 3-Year Constant Maturity, Quoted on an Investment Basis' },
  { id: 'BAMLEMFSFCRPIOAS', title: 'ICE BofA Private Sector Financial Emerging Markets Corporate Plus Index Option-Adjusted Spread' },
  { id: 'TGCR99THPERCENTILE', title: 'Tri-Party General Collateral Rate: 99th Percentile' },
  { id: 'BAMLEMHGHGLCRPIUSOAS', title: 'ICE BofA High Grade US Emerging Markets Liquid Corporate Plus Index Option-Adjusted Spread' },
  { id: 'OBFR99', title: 'Overnight Bank Funding Rate: 99th Percentile' },
  { id: 'BAMLC8A0C15PY', title: 'ICE BofA 15+ Year US Corporate Index Option-Adjusted Spread' },
  { id: 'BAMLEMFLFLCRPIUSOAS', title: 'ICE BofA Financial US Emerging Markets Liquid Corporate Plus Index Option-Adjusted Spread' },
  { id: 'BAMLH0A0HYM2EY', title: 'ICE BofA US High Yield Index Effective Yield' },
  { id: 'BAMLEM1BRRAAA2ACRPISYTW', title: 'ICE BofA AAA-A Emerging Markets Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'RIFSPPNA2P2D07NB', title: '7-Day A2/P2 Nonfinancial Commercial Paper Interest Rate' },
  { id: 'BAMLC0A2CAA', title: 'ICE BofA AA US Corporate Index Option-Adjusted Spread' },
  { id: 'BAMLEM1RAAA2ALCRPIUSEY', title: 'ICE BofA AAA-A US Emerging Markets Liquid Corporate Plus Index Effective Yield' },
  { id: 'BAMLC0A3CA', title: 'ICE BofA Single-A US Corporate Index Option-Adjusted Spread' },
  { id: 'NONFIN1020AAAMT', title: 'Total Value of Issues, with a Maturity Between 10 and 20 Days, Used in Calculating the AA Nonfinancial Commercial Paper Rates' },
  { id: 'RPONTTLD', title: 'Overnight Repurchase Agreements: Total Securities Purchased by the Federal Reserve in the Temporary Open Market Operations' },
  { id: 'RPTTLD', title: 'Repurchase Agreements: Total Securities Purchased by the Federal Reserve in the Temporary Open Market Operations' },
  { id: 'RIFSPPNA2P2D01NB', title: 'Overnight A2/P2 Nonfinancial Commercial Paper Interest Rate' },
  { id: 'BAMLH0A1HYBBSYTW', title: 'ICE BofA BB US High Yield Index Semi-Annual Yield to Worst' },
  { id: 'DGS5', title: 'Market Yield on U.S. Treasury Securities at 5-Year Constant Maturity, Quoted on an Investment Basis' },
  { id: 'T5YFF', title: '5-Year Treasury Constant Maturity Minus Federal Funds Rate' },
  { id: 'BAMLC0A4CBBB', title: 'ICE BofA BBB US Corporate Index Option-Adjusted Spread' },
  { id: 'BAMLC0A0CM', title: 'ICE BofA US Corporate Index Option-Adjusted Spread' },
  { id: 'BAMLHE00EHYIEY', title: 'ICE BofA Euro High Yield Index Effective Yield' },
  { id: 'SOFR99', title: 'Secured Overnight Financing Rate: 99th Percentile' },
  { id: 'BAMLH0A2HYBEY', title: 'ICE BofA Single-B US High Yield Index Effective Yield' },
  { id: 'BAMLEMRACRPIASIAOAS', title: 'ICE BofA Asia Emerging Markets Corporate Plus Index Option-Adjusted Spread' },
  { id: 'BAMLEMLLLCRPILAUSOAS', title: 'ICE BofA Latin America US Emerging Markets Liquid Corporate Plus Index Option-Adjusted Spread' },
  { id: 'BAMLEM1BRRAAA2ACRPIEY', title: 'ICE BofA AAA-A Emerging Markets Corporate Plus Index Effective Yield' },
  { id: 'DGS7', title: 'Market Yield on U.S. Treasury Securities at 7-Year Constant Maturity, Quoted on an Investment Basis' },
  { id: 'DGS10', title: 'Market Yield on U.S. Treasury Securities at 10-Year Constant Maturity, Quoted on an Investment Basis' },
  { id: 'T10YFF', title: '10-Year Treasury Constant Maturity Minus Federal Funds Rate' },
  { id: 'BAMLHE00EHYISYTW', title: 'ICE BofA Euro High Yield Index Semi-Annual Yield to Worst' },
  { id: 'DGS2', title: 'Market Yield on U.S. Treasury Securities at 2-Year Constant Maturity, Quoted on an Investment Basis' },
  { id: 'FIN14AAVOL', title: 'Number of Issues, with a Maturity Between 1 and 4 Days, Used in Calculating the AA Financial Commercial Paper Rates' },
  { id: 'BAMLC1A0C13YEY', title: 'ICE BofA 1-3 Year US Corporate Index Effective Yield' },
  { id: 'BAMLC1A0C13YSYTW', title: 'ICE BofA 1-3 Year US Corporate Index Semi-Annual Yield to Worst' },
  { id: 'BAMLC7A0C1015Y', title: 'ICE BofA 10-15 Year US Corporate Index Option-Adjusted Spread' },
  { id: 'SOFRVOL', title: 'Secured Overnight Financing Volume' },
  { id: 'BAMLC2A0C35Y', title: 'ICE BofA 3-5 Year US Corporate Index Option-Adjusted Spread' },
  { id: 'BAMLEMNFNFLCRPIUSOAS', title: 'ICE BofA Non-Financial US Emerging Markets Liquid Corporate Plus Index Option-Adjusted Spread' },
  { id: 'BAMLEMNSNFCRPIOAS', title: 'ICE BofA Non-Financial Emerging Markets Corporate Plus Index Option-Adjusted Spread' },
  { id: 'BAMLC0A2CAAEY', title: 'ICE BofA AA US Corporate Index Effective Yield' },
  { id: 'BAMLEMCLLCRPIUSOAS', title: 'ICE BofA US Emerging Markets Liquid Corporate Plus Index Option-Adjusted Spread' },
  { id: 'AB2140AAVOL', title: 'Number of Issues, with a Maturity Between 21 and 40 Days, Used in Calculating the AA Asset-Backed Commercial Paper Rates' },
  { id: 'SOFR', title: 'Secured Overnight Financing Rate' },
  { id: 'BAMLC0A2CAASYTW', title: 'ICE BofA AA US Corporate Index Semi-Annual Yield to Worst' },
  { id: 'BAMLEMRLCRPILAOAS', title: 'ICE BofA Latin America Emerging Markets Corporate Plus Index Option-Adjusted Spread' },
  { id: 'BAMLEMHGHGLCRPIUSEY', title: 'ICE BofA High Grade US Emerging Markets Liquid Corporate Plus Index Effective Yield' },
  { id: 'BAMLEMPVPRIVSLCRPIUSOAS', title: 'ICE BofA Private Sector Issuers US Emerging Markets Liquid Corporate Plus Index Option-Adjusted Spread' },
  { id: 'BAMLC2A0C35YEY', title: 'ICE BofA 3-5 Year US Corporate Index Effective Yield' },
  { id: 'MKT59MKTVOL', title: 'Number of Commercial Paper Issues with a Maturity Between 5 and 9 Days' },
  { id: 'BAMLEMRACRPIASIAEY', title: 'ICE BofA Asia Emerging Markets Corporate Plus Index Effective Yield' },
  { id: 'ABGT80AAVOL', title: 'Number of Issues, with a Maturity Greater Than 80 Days, Used in Calculating the AA Asset-Backed Commercial Paper Rates' },
  { id: 'BAMLEMCBPIOAS', title: 'ICE BofA Emerging Markets Corporate Plus Index Option-Adjusted Spread' },
  { id: 'NONFIN14AAVOL', title: 'Number of Issues, with a Maturity Between 1 and 4 Days, Used in Calculating the AA Nonfinancial Commercial Paper Rates' },
  { id: 'BAMLEMUBCRPIUSOAS', title: 'ICE BofA US Emerging Markets Corporate Plus Index Option-Adjusted Spread' },
  { id: 'BAMLEMPUPUBSLCRPIUSSYTW', title: 'ICE BofA Public Sector Issuers US Emerging Markets Liquid Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'NONFIN1020AAVOL', title: 'Number of Issues, with a Maturity Between 10 and 20 Days, Used in Calculating the AA Nonfinancial Commercial Paper Rates' },
  { id: 'BAMLEMIBHGCRPIEY', title: 'ICE BofA High Grade Emerging Markets Corporate Plus Index Effective Yield' },
  { id: 'BAMLC0A1CAAAEY', title: 'ICE BofA AAA US Corporate Index Effective Yield' },
  { id: 'T10YIE', title: '10-Year Breakeven Inflation Rate' },
  { id: 'BAMLEM3RBBLCRPIUSOAS', title: 'ICE BofA BB US Emerging Markets Liquid Corporate Plus Index Option-Adjusted Spread' },
  { id: 'BAMLEMHGHGLCRPIUSSYTW', title: 'ICE BofA High Grade US Emerging Markets Liquid Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'RPONMBSD', title: 'Overnight Repurchase Agreements: Mortgage-Backed Securities Purchased by the Federal Reserve in the Temporary Open Market Operations' },
  { id: 'RPMBSD', title: 'Repurchase Agreements: Mortgage-Backed Securities Purchased by the Federal Reserve in the Temporary Open Market Operations' },
  { id: 'BAMLEMPTPRVICRPIOAS', title: 'ICE BofA Private Sector Issuers Emerging Markets Corporate Plus Index Option-Adjusted Spread' },
  { id: 'BAMLC0A1CAAASYTW', title: 'ICE BofA AAA US Corporate Index Semi-Annual Yield to Worst' },
  { id: 'BAMLEMPUPUBSLCRPIUSEY', title: 'ICE BofA Public Sector Issuers US Emerging Markets Liquid Corporate Plus Index Effective Yield' },
  { id: 'BAMLEMELLCRPIEMEAUSEY', title: 'ICE BofA EMEA US Emerging Markets Liquid Corporate Plus Index Effective Yield' },
  { id: 'USEPUINDXD', title: 'Economic Policy Uncertainty Index for United States' },
  { id: 'BAMLEM3BRRBBCRPIOAS', title: 'ICE BofA BB Emerging Markets Corporate Plus Index Option-Adjusted Spread' },
  { id: 'BAMLC0A3CASYTW', title: 'ICE BofA Single-A US Corporate Index Semi-Annual Yield to Worst' },
  { id: 'BAMLEMRACRPIASIASYTW', title: 'ICE BofA Asia Emerging Markets Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'BAMLEMIBHGCRPISYTW', title: 'ICE BofA High Grade Emerging Markets Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'SOFR25', title: 'Secured Overnight Financing Rate: 25th Percentile' },
  { id: 'BAMLC2A0C35YSYTW', title: 'ICE BofA 3-5 Year US Corporate Index Semi-Annual Yield to Worst' },
  { id: 'MKT59MKTAMT', title: 'Total Value of Issuers of Commercial Paper with a Maturity Between 5 and 9 Days' },
  { id: 'TGCR25THPERCENTILE', title: 'Tri-Party General Collateral Rate: 25th Percentile' },
  { id: 'BAMLC3A0C57YSYTW', title: 'ICE BofA 5-7 Year US Corporate Index Semi-Annual Yield to Worst' },
  { id: 'BAMLEMPBPUBSICRPISYTW', title: 'ICE BofA Public Sector Issuers Emerging Markets Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'BAMLC0A0CMSYTW', title: 'ICE BofA US Corporate Index Semi-Annual Yield to Worst' },
  { id: 'BAMLEMALLCRPIASIAUSEY', title: 'ICE BofA Asia US Emerging Markets Liquid Corporate Plus Index Effective Yield' },
  { id: 'TGCRRATE', title: 'Tri-Party General Collateral Rate' },
  { id: 'DGS1', title: 'Market Yield on U.S. Treasury Securities at 1-Year Constant Maturity, Quoted on an Investment Basis' },
  { id: 'T1YFF', title: '1-Year Treasury Constant Maturity Minus Federal Funds Rate' },
  { id: 'T5YIFR', title: '5-Year, 5-Year Forward Inflation Expectation Rate' },
  { id: 'BAMLC0A3CAEY', title: 'ICE BofA Single-A US Corporate Index Effective Yield' },
  { id: 'TGCR75THPERCENTILE', title: 'Tri-Party General Collateral Rate: 75th Percentile' },
  { id: 'NONFINGT80AAVOL', title: 'Number of Issues, with a Maturity Greater Than 80 Days, Used in Calculating the AA Nonfinancial Commercial Paper Rates' },
  { id: 'BAMLEMPBPUBSICRPIEY', title: 'ICE BofA Public Sector Issuers Emerging Markets Corporate Plus Index Effective Yield' },
  { id: 'BAMLC0A4CBBBEY', title: 'ICE BofA BBB US Corporate Index Effective Yield' },
  { id: 'WLEMUINDXD', title: 'Equity Market-related Economic Uncertainty Index' },
  { id: 'FIN4180AAAMT', title: 'Total Value of Issues, with a Maturity Between 41 and 80 Days, Used in Calculating the AA Financial Commercial Paper Rates' },
  { id: 'DGS30', title: 'Market Yield on U.S. Treasury Securities at 30-Year Constant Maturity, Quoted on an Investment Basis' },
  { id: 'DTB1YR', title: '1-Year Treasury Bill Secondary Market Rate, Discount Basis' },
  { id: 'BAMLC3A0C57YEY', title: 'ICE BofA 5-7 Year US Corporate Index Effective Yield' },
  { id: 'BAMLEMALLCRPIASIAUSSYTW', title: 'ICE BofA Asia US Emerging Markets Liquid Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'BAA10Y', title: 'Moody\'s Seasoned Baa Corporate Bond Yield Relative to Yield on 10-Year Treasury Constant Maturity' },
  { id: 'SOFR75', title: 'Secured Overnight Financing Rate: 75th Percentile' },
  { id: 'BAMLC0A0CMEY', title: 'ICE BofA US Corporate Index Effective Yield' },
  { id: 'BAMLEMELLCRPIEMEAUSSYTW', title: 'ICE BofA EMEA US Emerging Markets Liquid Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'DGS20', title: 'Market Yield on U.S. Treasury Securities at 20-Year Constant Maturity, Quoted on an Investment Basis' },
  { id: 'MKT4180MKTAMT', title: 'Total Value of Issuers of Commercial Paper with a Maturity Between 41 and 80 Days' },
  { id: 'ABGT80AAAMT', title: 'Total Value of Issues, with a Maturity Greater Than 80 Days, Used in Calculating the AA Asset-Backed Commercial Paper Rates' },
  { id: 'NONFINGT80AAAMT', title: 'Total Value of Issues, with a Maturity Greater Than 80 Days, Used in Calculating the AA Nonfinancial Commercial Paper Rates' },
  { id: 'BAMLEMPUPUBSLCRPIUSOAS', title: 'ICE BofA Public Sector Issuers US Emerging Markets Liquid Corporate Plus Index Option-Adjusted Spread' },
  { id: 'NONFIN14AAAMT', title: 'Total Value of Issues, with a Maturity Between 1 and 4 Days, Used in Calculating the AA Nonfinancial Commercial Paper Rates' },
  { id: 'FIN14AAAMT', title: 'Total Value of Issues, with a Maturity Between 1 and 4 Days, Used in Calculating the AA Financial Commercial Paper Rates' },
  { id: 'BAMLEMCBPIEY', title: 'ICE BofA Emerging Markets Corporate Plus Index Effective Yield' },
  { id: 'RIFSPPAAAD30NB', title: '30-Day AA Asset-Backed Commercial Paper Interest Rate' },
  { id: 'MKT4180MKTVOL', title: 'Number of Commercial Paper Issues with a Maturity Between 41 and 80 Days' },
  { id: 'BAMLEMCLLCRPIUSEY', title: 'ICE BofA US Emerging Markets Liquid Corporate Plus Index Effective Yield' },
  { id: 'AB2140AAAMT', title: 'Total Value of Issues, with a Maturity Between 21 and 40 Days, Used in Calculating the AA Asset-Backed Commercial Paper Rates' },
  { id: 'FIN4180AAVOL', title: 'Number of Issues, with a Maturity Between 41 and 80 Days, Used in Calculating the AA Financial Commercial Paper Rates' },
  { id: 'DGS3MO', title: 'Market Yield on U.S. Treasury Securities at 3-Month Constant Maturity, Quoted on an Investment Basis' },
  { id: 'T3MFF', title: '3-Month Treasury Constant Maturity Minus Federal Funds Rate' },
  { id: 'BAMLEM1BRRAAA2ACRPIOAS', title: 'ICE BofA AAA-A Emerging Markets Corporate Plus Index Option-Adjusted Spread' },
  { id: 'NONFINGT80A2P2VOL', title: 'Number of Issues, with a Maturity Greater Than 80 Days, Used in Calculating the A2/P2 Nonfinancial Commercial Paper Rates' },
  { id: 'BAMLC0A4CBBBSYTW', title: 'ICE BofA BBB US Corporate Index Semi-Annual Yield to Worst' },
  { id: 'BAMLEMHYHYLCRPIUSOAS', title: 'ICE BofA High Yield US Emerging Markets Liquid Corporate Plus Index Option-Adjusted Spread' },
  { id: 'BAMLEMUBCRPIUSEY', title: 'ICE BofA US Emerging Markets Corporate Plus Index Effective Yield' },
  { id: 'BAMLEMRECRPIEMEASYTW', title: 'ICE BofA EMEA Emerging Markets Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'OBMMIC30YFLVGT80FB720A739', title: '30-Year Fixed Rate Conforming Mortgage Index: Loan-to-Value Greater Than 80, FICO Score Between 720 and 739' },
  { id: 'BAMLEMRECRPIEMEAEY', title: 'ICE BofA EMEA Emerging Markets Corporate Plus Index Effective Yield' },
  { id: 'AB1020AAAMT', title: 'Total Value of Issues, with a Maturity Between 10 and 20 Days, Used in Calculating the AA Asset-Backed Commercial Paper Rates' },
  { id: 'EFFR99', title: 'Effective Federal Funds Rate: 99th Percentile' },
  { id: 'DTB3', title: '3-Month Treasury Bill Secondary Market Rate, Discount Basis' },
  { id: 'RRPONTSYD', title: 'Overnight Reverse Repurchase Agreements: Treasury Securities Sold by the Federal Reserve in the Temporary Open Market Operations' },
  { id: 'RRPONTTLD', title: 'Overnight Reverse Repurchase Agreements: Total Securities Sold by the Federal Reserve in the Temporary Open Market Operations' },
  { id: 'RRPTSYD', title: 'Reverse Repurchase Agreements: Treasury Securities Sold by the Federal Reserve in the Temporary Open Market Operations' },
  { id: 'RRPONTSYSAD', title: 'Overnight Reverse Repurchase Agreements: Amount of Treasury Securities Submitted' },
  { id: 'RRPTTLD', title: 'Reverse Repurchase Agreements: Total Securities Sold by the Federal Reserve in the Temporary Open Market Operations' },
  { id: 'BAMLEMPBPUBSICRPIOAS', title: 'ICE BofA Public Sector Issuers Emerging Markets Corporate Plus Index Option-Adjusted Spread' },
  { id: 'AB4180AAVOL', title: 'Number of Issues, with a Maturity Between 41 and 80 Days, Used in Calculating the AA Asset-Backed Commercial Paper Rates' },
  { id: 'BAMLEMUBCRPIUSSYTW', title: 'ICE BofA US Emerging Markets Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'FIN1020AAAMT', title: 'Total Value of Issues, with a Maturity Between 10 and 20 Days, Used in Calculating the AA Financial Commercial Paper Rates' },
  { id: 'DTP30F45', title: '30-Year 0-3/4% Treasury Inflation-Indexed Bond, Due 2/15/2045' },
  { id: 'DFII10', title: 'Market Yield on U.S. Treasury Securities at 10-Year Constant Maturity, Quoted on an Investment Basis, Inflation-Indexed' },
  { id: 'OBMMIFHA30YF', title: '30-Year Fixed Rate FHA Mortgage Index' },
  { id: 'DTP30F40', title: '30-Year 2-1/8% Treasury Inflation-Indexed Bond, Due 2/15/2040' },
  { id: 'DTP30F44', title: '30-Year 1-3/8% Treasury Inflation-Indexed Note, Due 2/15/2044' },
  { id: 'RIFSPPAAAD90NB', title: '90-Day AA Asset-Backed Commercial Paper Interest Rate' },
  { id: 'RIFSPPAAAD15NB', title: '15-Day AA Asset-Backed Commercial Paper Interest Rate' },
  { id: 'DTP30F41', title: '30-Year 2-1/8% Treasury Inflation-Indexed Bond, Due 2/15/2041' },
  { id: 'BAMLEMELLCRPIEMEAUSOAS', title: 'ICE BofA EMEA US Emerging Markets Liquid Corporate Plus Index Option-Adjusted Spread' },
  { id: 'FIN1020AAVOL', title: 'Number of Issues, with a Maturity Between 10 and 20 Days, Used in Calculating the AA Financial Commercial Paper Rates' },
  { id: 'DTP30F48', title: '30-Year 1.0% Treasury Inflation-Indexed Bond, Due 2/15/2048' },
  { id: 'SOFR1', title: 'Secured Overnight Financing Rate: 1st Percentile' },
  { id: 'DFII20', title: 'Market Yield on U.S. Treasury Securities at 20-Year Constant Maturity, Quoted on an Investment Basis, Inflation-Indexed' },
  { id: 'DTP30F42', title: '30-Year 0-3/4% Treasury Inflation-Indexed Bond, Due 2/15/2042' },
  { id: 'BAMLEMCBPISYTW', title: 'ICE BofA Emerging Markets Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'AB59AAAMT', title: 'Total Value of Issues, with a Maturity Between 5 and 9 Days, Used in Calculating the AA Asset-Backed Commercial Paper Rates' },
  { id: 'DTP30F49', title: '30-Year 1.0% Treasury Inflation-Indexed Bond, Due 2/15/2049' },
  { id: 'DTP30F46', title: '30-Year 1.0% Treasury Inflation-Indexed Bond, Due 2/15/2046' },
  { id: 'BAMLEMHBHYCRPIOAS', title: 'ICE BofA High Yield Emerging Markets Corporate Plus Index Option-Adjusted Spread' },
  { id: 'DTP30F47', title: '30-Year 0.875% Treasury Inflation-Indexed Bond, Due 2/15/2047' },
  { id: 'AB59AAVOL', title: 'Number of Issues, with a Maturity Between 5 and 9 Days, Used in Calculating the AA Asset-Backed Commercial Paper Rates' },
  { id: 'DLTIIT', title: 'Treasury Long-Term Average (Over 10 Years), Inflation-Indexed' },
  { id: 'RIFSPPNA2P2D15NB', title: '15-Day A2/P2 Nonfinancial Commercial Paper Interest Rate' },
  { id: 'DTP30F43', title: '30-Year 0-5/8% Treasury Inflation-Indexed Bond, Due 2/15/2043' },
  { id: 'BAMLEMRECRPIEMEAOAS', title: 'ICE BofA EMEA Emerging Markets Corporate Plus Index Option-Adjusted Spread' },
  { id: 'DTP30F50', title: '30-Year 0.250% Treasury Inflation-Indexed Bond, Due 02/15/2050' },
  { id: 'OBMMIJUMBO30YF', title: '30-Year Fixed Rate Jumbo Mortgage Index' },
  { id: 'BAMLEM1RAAA2ALCRPIUSOAS', title: 'ICE BofA AAA-A US Emerging Markets Liquid Corporate Plus Index Option-Adjusted Spread' },
  { id: 'RIFSPPAAAD07NB', title: '7-Day AA Asset-Backed Commercial Paper Interest Rate' },
  { id: 'BAMLC4A0C710YSYTW', title: 'ICE BofA 7-10 Year US Corporate Index Semi-Annual Yield to Worst' },
  { id: 'BAMLEMCLLCRPIUSSYTW', title: 'ICE BofA US Emerging Markets Liquid Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'BAMLC7A0C1015YEY', title: 'ICE BofA 10-15 Year US Corporate Index Effective Yield' },
  { id: 'MKT14MKTAMT', title: 'Total Value of Commercial Paper Issues with a Maturity Between 1 and 4 Days' },
  { id: 'SOFR180DAYAVG', title: '180-Day Average SOFR' },
  { id: 'IUDZOS2', title: 'SONIA Compounded Index' },
  { id: 'SOFRINDEX', title: 'SOFR Index' },
  { id: 'DFII30', title: 'Market Yield on U.S. Treasury Securities at 30-Year Constant Maturity, Quoted on an Investment Basis, Inflation-Indexed' },
  { id: 'OBFR', title: 'Overnight Bank Funding Rate' },
  { id: 'DFII7', title: 'Market Yield on U.S. Treasury Securities at 7-Year Constant Maturity, Quoted on an Investment Basis, Inflation-Indexed' },
  { id: 'DBAA', title: 'Moody\'s Seasoned Baa Corporate Bond Yield' },
  { id: 'BAAFF', title: 'Moody\'s Seasoned Baa Corporate Bond Minus Federal Funds Rate' },
  { id: 'BAMLEM4BRRBLCRPIEY', title: 'ICE BofA B & Lower Emerging Markets Corporate Plus Index Effective Yield' },
  { id: 'BAMLH0A1HYBBEY', title: 'ICE BofA BB US High Yield Index Effective Yield' },
  { id: 'BAMLEMFLFLCRPIUSSYTW', title: 'ICE BofA Financial US Emerging Markets Liquid Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'BAMLEM4RBLLCRPIUSEY', title: 'ICE BofA B & Lower US Emerging Markets Liquid Corporate Plus Index Effective Yield' },
  { id: 'BAMLEMFSFCRPIEY', title: 'ICE BofA Private Sector Financial Emerging Markets Corporate Plus Index Effective Yield' },
  { id: 'BAMLC4A0C710YEY', title: 'ICE BofA 7-10 Year US Corporate Index Effective Yield' },
  { id: 'BAMLC7A0C1015YSYTW', title: 'ICE BofA 10-15 Year US Corporate Index Semi-Annual Yield to Worst' },
  { id: 'ECBESTRNUMACTBANKS', title: 'Euro Short-Term Rate: Number of Active Banks' },
  { id: 'BAMLC8A0C15PYSYTW', title: 'ICE BofA 15+ Year US Corporate Index Semi-Annual Yield to Worst' },
  { id: 'BAMLC8A0C15PYEY', title: 'ICE BofA 15+ Year US Corporate Index Effective Yield' },
  { id: 'AB4180AAAMT', title: 'Total Value of Issues, with a Maturity Between 41 and 80 Days, Used in Calculating the AA Asset-Backed Commercial Paper Rates' },
  { id: 'RPONAGYD', title: 'Overnight Repurchase Agreements: Federal Agency Securities Purchased by the Federal Reserve in the Temporary Open Market Operations' },
  { id: 'RPAGYD', title: 'Repurchase Agreements: Federal Agency Securities Purchased by the Federal Reserve in the Temporary Open Market Operations' },
  { id: 'EFFR25', title: 'Effective Federal Funds Rate: 25th Percentile' },
  { id: 'SOFR90DAYAVG', title: '90-Day Average SOFR' },
  { id: 'OBMMIC30YFLVLE80FB680A699', title: '30-Year Fixed Rate Conforming Mortgage Index: Loan-to-Value Less Than or Equal to 80, FICO Score Between 680 and 699' },
  { id: 'BAMLEMFLFLCRPIUSEY', title: 'ICE BofA Financial US Emerging Markets Liquid Corporate Plus Index Effective Yield' },
  { id: 'BAMLEM4BRRBLCRPISYTW', title: 'ICE BofA B & Lower Emerging Markets Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'AB1020AAVOL', title: 'Number of Issues, with a Maturity Between 10 and 20 Days, Used in Calculating the AA Asset-Backed Commercial Paper Rates' },
  { id: 'BAMLEMPTPRVICRPIEY', title: 'ICE BofA Private Sector Issuers Emerging Markets Corporate Plus Index Effective Yield' },
  { id: 'AB14AAVOL', title: 'Number of Issues, with a Maturity Between 1 and 4 Days, Used in Calculating the AA Asset-Backed Commercial Paper Rates' },
  { id: 'BAMLEMPVPRIVSLCRPIUSEY', title: 'ICE BofA Private Sector Issuers US Emerging Markets Liquid Corporate Plus Index Effective Yield' },
  { id: 'T5YIE', title: '5-Year Breakeven Inflation Rate' },
  { id: 'MKT2140MKTAMT', title: 'Total Value of Issuers of Commercial Paper with a Maturity Between 21 and 40 Days' },
  { id: 'DTP3HA32', title: '30-1/2-Year 3-3/8% Treasury Inflation-Indexed Bond, Due 4/15/2032' },
  { id: 'FIN2140AAVOL', title: 'Number of Issues, with a Maturity Between 21 and 40 Days, Used in Calculating the AA Financial Commercial Paper Rates' },
  { id: 'BAMLEM4RBLLCRPIUSSYTW', title: 'ICE BofA B & Lower US Emerging Markets Liquid Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'DAAA', title: 'Moody\'s Seasoned Aaa Corporate Bond Yield' },
  { id: 'AAAFF', title: 'Moody\'s Seasoned Aaa Corporate Bond Minus Federal Funds Rate' },
  { id: 'BAMLEMEBCRPIEEY', title: 'ICE BofA Euro Emerging Markets Corporate Plus Index Effective Yield' },
  { id: 'DTB4WK', title: '4-Week Treasury Bill Secondary Market Rate, Discount Basis' },
  { id: 'NONFIN2140A2P2VOL', title: 'Number of Issues, with a Maturity Between 21 and 40 Days, Used in Calculating the A2/P2 Nonfinancial Commercial Paper Rates' },
  { id: 'DGS6MO', title: 'Market Yield on U.S. Treasury Securities at 6-Month Constant Maturity, Quoted on an Investment Basis' },
  { id: 'T6MFF', title: '6-Month Treasury Constant Maturity Minus Federal Funds Rate' },
  { id: 'BAMLEMLLLCRPILAUSEY', title: 'ICE BofA Latin America US Emerging Markets Liquid Corporate Plus Index Effective Yield' },
  { id: 'MKT14MKTVOL', title: 'Number of Commercial Paper Issues with a Maturity Between 1 and 4 Days' },
  { id: 'BAMLEMFSFCRPISYTW', title: 'ICE BofA Private Sector Financial Emerging Markets Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'MKT2140MKTVOL', title: 'Number of Commercial Paper Issues with a Maturity Between 21 and 40 Days' },
  { id: 'ECBESTRRT25THPCTVOL', title: 'Euro Short-Term Rate: Rate at 25th Percentile of Volume' },
  { id: 'BAMLC1A0C13Y', title: 'ICE BofA 1-3 Year US Corporate Index Option-Adjusted Spread' },
  { id: 'DFII5', title: 'Market Yield on U.S. Treasury Securities at 5-Year Constant Maturity, Quoted on an Investment Basis, Inflation-Indexed' },
  { id: 'OBMMIC15YF', title: '15-Year Fixed Rate Conforming Mortgage Index' },
  { id: 'BAMLEMEBCRPIESYTW', title: 'ICE BofA Euro Emerging Markets Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'T10Y2Y', title: '10-Year Treasury Constant Maturity Minus 2-Year Treasury Constant Maturity' },
  { id: 'AB14AAAMT', title: 'Total Value of Issues, with a Maturity Between 1 and 4 Days, Used in Calculating the AA Asset-Backed Commercial Paper Rates' },
  { id: 'FINGT80AAAMT', title: 'Total Value of Issues, with a Maturity Greater Than 80 Days, Used in Calculating the AA Financial Commercial Paper Rates' },
  { id: 'OBFR25', title: 'Overnight Bank Funding Rate: 25th Percentile' },
  { id: 'FINGT80AAVOL', title: 'Number of Issues, with a Maturity Greater Than 80 Days, Used in Calculating the AA Financial Commercial Paper Rates' },
  { id: 'MKT1020MKTVOL', title: 'Number of Commercial Paper Issues with a Maturity Between 10 and 20 Days' },
  { id: 'BAMLEMNSNFCRPIEY', title: 'ICE BofA Non-Financial Emerging Markets Corporate Plus Index Effective Yield' },
  { id: 'INFECTDISEMVTRACKD', title: 'Equity Market Volatility: Infectious Disease Tracker' },
  { id: 'BAMLEMPTPRVICRPISYTW', title: 'ICE BofA Private Sector Issuers Emerging Markets Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'DTP10L26', title: '10-Year 0-1/8% Treasury Inflation-Indexed Note, Due 7/15/2026' },
  { id: 'BAMLEMNSNFCRPISYTW', title: 'ICE BofA Non-Financial Emerging Markets Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'TGCRVOLUME', title: 'Tri-Party General Collateral Rate Volume' },
  { id: 'OBFRVOL', title: 'Overnight Bank Funding Volume' },
  { id: 'NONFIN4180AAAMT', title: 'Total Value of Issues, with a Maturity Between 41 and 80 Days, Used in Calculating the AA Nonfinancial Commercial Paper Rates' },
  { id: 'OBMMIC30YFLVLE80FB720A739', title: '30-Year Fixed Rate Conforming Mortgage Index: Loan-to-Value Less Than or Equal to 80, FICO Score Between 720 and 739' },
  { id: 'ECBESTRNUMTRANS', title: 'Euro Short-Term Rate: Number of Transactions' },
  { id: 'NONFIN59AAAMT', title: 'Total Value of Issues, with a Maturity Between 5 and 9 Days, Used in Calculating the AA Nonfinancial Commercial Paper Rates' },
  { id: 'BAMLEMEBCRPIEOAS', title: 'ICE BofA Euro Emerging Markets Corporate Plus Index Option-Adjusted Spread' },
  { id: 'ECBESTRTOTVOL', title: 'Euro Short-Term Rate: Total Volume' },
  { id: 'ECBESTRVOLWGTTRMDMNRT', title: 'Euro Short-Term Rate: Volume-Weighted Trimmed Mean Rate' },
  { id: 'ECBESTRSHRVOL5LRGACTBNK', title: 'Euro Short-Term Rate: Share of Volume of the 5 Largest Active Banks' },
  { id: 'OBMMIC30YFLVGT80FLT680', title: '30-Year Fixed Rate Conforming Mortgage Index: Loan-to-Value Greater Than 80, FICO Score Less Than 680' },
  { id: 'FIN2140AAAMT', title: 'Total Value of Issues, with a Maturity Between 21 and 40 Days, Used in Calculating the AA Financial Commercial Paper Rates' },
  { id: 'BAMLEMPVPRIVSLCRPIUSSYTW', title: 'ICE BofA Private Sector Issuers US Emerging Markets Liquid Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'DTB6', title: '6-Month Treasury Bill Secondary Market Rate, Discount Basis' },
  { id: 'BAMLEM2BRRBBBCRPISYTW', title: 'ICE BofA BBB Emerging Markets Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'NONFIN4180A2P2AMT', title: 'Total Value of Issues, with a Maturity Between 41 and 80 Days, Used in Calculating the A2/P2 Nonfinancial Commercial Paper Rates' },
  { id: 'DTP10J30', title: '10-Year 0.125% Treasury Inflation-Indexed Bond, Due 01/15/2030' },
  { id: 'NONFIN1020A2P2VOL', title: 'Number of Issues, with a Maturity Between 10 and 20 Days, Used in Calculating the A2/P2 Nonfinancial Commercial Paper Rates' },
  { id: 'NONFIN59AAVOL', title: 'Number of Issues, with a Maturity Between 5 and 9 Days, Used in Calculating the AA Nonfinancial Commercial Paper Rates' },
  { id: 'BAMLEMLLLCRPILAUSSYTW', title: 'ICE BofA Latin America US Emerging Markets Liquid Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'RIFSPPAAAD60NB', title: '60-Day AA Asset-Backed Commercial Paper Interest Rate' },
  { id: 'OBMMIC30YFLVGT80FB680A699', title: '30-Year Fixed Rate Conforming Mortgage Index: Loan-to-Value Greater Than 80, FICO Score Between 680 and 699' },
  { id: 'RIFSPPFAAD01NB', title: 'Overnight AA Financial Commercial Paper Interest Rate' },
  { id: 'BAMLEM3RBBLCRPIUSSYTW', title: 'ICE BofA BB US Emerging Markets Liquid Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'BAMLEMXOCOLCRPIUSSYTW', title: 'ICE BofA Crossover US Emerging Markets Liquid Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'BAMLEMHBHYCRPIEY', title: 'ICE BofA High Yield Emerging Markets Corporate Plus Index Effective Yield' },
  { id: 'BAMLEMHBHYCRPISYTW', title: 'ICE BofA High Yield Emerging Markets Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'OBMMIUSDA30YF', title: '30-Year Fixed Rate USDA Mortgage Index' },
  { id: 'BAMLEM2RBBBLCRPIUSSYTW', title: 'ICE BofA BBB US Emerging Markets Liquid Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'BAMLEM2BRRBBBCRPIEY', title: 'ICE BofA BBB Emerging Markets Corporate Plus Index Effective Yield' },
  { id: 'OBMMIC30YFLVLE80FB700A719', title: '30-Year Fixed Rate Conforming Mortgage Index: Loan-to-Value Less Than or Equal to 80, FICO Score Between 700 and 719' },
  { id: 'EFFRVOL', title: 'Effective Federal Funds Volume' },
  { id: 'NONFINGT80A2P2AMT', title: 'Total Value of Issues, with a Maturity Greater Than 80 Days, Used in Calculating the A2/P2 Nonfinancial Commercial Paper Rates' },
  { id: 'DTP30A29', title: '30-Year 3-7/8% Treasury Inflation-Indexed Bond, Due 4/15/2029' },
  { id: 'DTP10L29', title: '10-Year 0.25% Treasury Inflation-Indexed Note, Due 7/15/2029' },
  { id: 'NONFIN1020A2P2AMT', title: 'Total Value of Issues, with a Maturity Between 10 and 20 Days, Used in Calculating the A2/P2 Nonfinancial Commercial Paper Rates' },
  { id: 'NONFIN4180AAVOL', title: 'Number of Issues, with a Maturity Between 41 and 80 Days, Used in Calculating the AA Nonfinancial Commercial Paper Rates' },
  { id: 'ECBESTRRT75THPCTVOL', title: 'Euro Short-Term Rate: Rate at 75th Percentile of Volume' },
  { id: 'BAMLEMNFNFLCRPIUSEY', title: 'ICE BofA Non-Financial US Emerging Markets Liquid Corporate Plus Index Effective Yield' },
  { id: 'DTP20J27', title: '20-Year 2-3/8% Treasury Inflation-Indexed Bond, Due 1/15/2027' },
  { id: 'DGS1MO', title: 'Market Yield on U.S. Treasury Securities at 1-Month Constant Maturity, Quoted on an Investment Basis' },
  { id: 'OBFR75', title: 'Overnight Bank Funding Rate: 75th Percentile' },
  { id: 'EFFR75', title: 'Effective Federal Funds Rate: 75th Percentile' },
  { id: 'BAMLEMHYHYLCRPIUSEY', title: 'ICE BofA High Yield US Emerging Markets Liquid Corporate Plus Index Effective Yield' },
  { id: 'DTP10J27', title: '10-Year 0.375 Treasury Inflation-Indexed Note, Due 1/15/2027' },
  { id: 'NONFIN2140AAAMT', title: 'Total Value of Issues, with a Maturity Between 21 and 40 Days, Used in Calculating the AA Nonfinancial Commercial Paper Rates' },
  { id: 'FIN59AAAMT', title: 'Total Value of Issues, with a Maturity Between 5 and 9 Days, Used in Calculating the AA Financial Commercial Paper Rates' },
  { id: 'NONFIN2140A2P2AMT', title: 'Total Value of Issues, with a Maturity Between 21 and 40 Days, Used in Calculating the A2/P2 Nonfinancial Commercial Paper Rates' },
  { id: 'OBMMIC30YFLVLE80FLT680', title: '30-Year Fixed Rate Conforming Mortgage Index: Loan-to-Value Less Than or Equal to 80, FICO Score Less Than 680' },
  { id: 'BAMLEMRLCRPILAEY', title: 'ICE BofA Latin America Emerging Markets Corporate Plus Index Effective Yield' },
  { id: 'DTP10J29', title: '10-Year 0.875% Treasury Inflation-Indexed Note, Due 1/15/2029' },
  { id: 'DTP20J29', title: '20-Year 2-1/2% Treasury Inflation-Indexed Bond, Due 1/15/2029' },
  { id: 'BAMLEMNFNFLCRPIUSSYTW', title: 'ICE BofA Non-Financial US Emerging Markets Liquid Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'BAMLEM3RBBLCRPIUSEY', title: 'ICE BofA BB US Emerging Markets Liquid Corporate Plus Index Effective Yield' },
  { id: 'OBMMIC30YFLVGT80FGE740', title: '30-Year Fixed Rate Conforming Mortgage Index: Loan-to-Value Greater Than 80, FICO Score Greater Than 740' },
  { id: 'MKTGT80MKTVOL', title: 'Number of Commercial Paper Issues with a Maturity Greater Than 80 Days' },
  { id: 'BAMLEM5BCOCRPIEY', title: 'ICE BofA Crossover Emerging Markets Corporate Plus Index Effective Yield' },
  { id: 'NONFIN2140AAVOL', title: 'Number of Issues, with a Maturity Between 21 and 40 Days, Used in Calculating the AA Nonfinancial Commercial Paper Rates' },
  { id: 'BAMLEMHYHYLCRPIUSSYTW', title: 'ICE BofA High Yield US Emerging Markets Liquid Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'MKT1020MKTAMT', title: 'Total Value of Commercial Paper Issues with a Maturity Between 10 and 20 Days' },
  { id: 'BAMLEM4BRRBLCRPIOAS', title: 'ICE BofA B & Lower Emerging Markets Corporate Plus Index Option-Adjusted Spread' },
  { id: 'OBMMIVA30YF', title: '30-Year Fixed Rate Veterans Affairs Mortgage Index' },
  { id: 'OBMMIC30YF', title: '30-Year Fixed Rate Conforming Mortgage Index' },
  { id: 'SOFR30DAYAVG', title: '30-Day Average SOFR' },
  { id: 'MKTGT80MKTAMT', title: 'Total Value of Issuers of Commercial Paper with a Maturity Greater Than 80 Days' },
  { id: 'NONFIN14A2P2AMT', title: 'Total Value of Issues, with a Maturity Between 1 and 4 Days, Used in Calculating the A2/P2 Nonfinancial Commercial Paper Rates' },
  { id: 'FIN59AAVOL', title: 'Number of Issues, with a Maturity Between 5 and 9 Days, Used in Calculating the AA Financial Commercial Paper Rates' },
  { id: 'NONFIN4180A2P2VOL', title: 'Number of Issues, with a Maturity Between 41 and 80 Days, Used in Calculating the A2/P2 Nonfinancial Commercial Paper Rates' },
  { id: 'DTP30A28', title: '30-Year 3-5/8% Treasury Inflation-Indexed Bond, Due 4/15/2028' },
  { id: 'DTP10L27', title: '10-Year 0.375% Treasury Inflation-Indexed Note, Due 7/15/2027' },
  { id: 'OBMMIC30YFLVLE80FGE740', title: '30-Year Fixed Rate Conforming Mortgage Index: Loan-to-Value Less Than or Equal to 80, FICO Score Greater Than 740' },
  { id: 'NONFIN14A2P2VOL', title: 'Number of Issues, with a Maturity Between 1 and 4 Days, Used in Calculating the A2/P2 Nonfinancial Commercial Paper Rates' },
  { id: 'DTP10J28', title: '10-Year 0.5% Treasury Inflation-Indexed Note, Due 1/15/2028' },
  { id: 'BAMLEMRLCRPILASYTW', title: 'ICE BofA Latin America Emerging Markets Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'DTP10L28', title: '10-Year 0.75% Treasury Inflation-Indexed Note, Due 7/15/2028' },
  { id: 'BAMLEMXOCOLCRPIUSEY', title: 'ICE BofA Crossover US Emerging Markets Liquid Corporate Plus Index Effective Yield' },
  { id: 'BAMLEM4RBLLCRPIUSOAS', title: 'ICE BofA B & Lower US Emerging Markets Liquid Corporate Plus Index Option-Adjusted Spread' },
  { id: 'BAMLEM2RBBBLCRPIUSEY', title: 'ICE BofA BBB US Emerging Markets Liquid Corporate Plus Index Effective Yield' },
  { id: 'BAMLEM3BRRBBCRPISYTW', title: 'ICE BofA BB Emerging Markets Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'BAMLEM5BCOCRPISYTW', title: 'ICE BofA Crossover Emerging Markets Corporate Plus Index Semi-Annual Yield to Worst' },
  { id: 'DTP20J28', title: '20-Year 1-3/4% Treasury Inflation-Indexed Bond, Due 1/15/2028' },
  { id: 'OBMMIC30YFLVGT80FB700A719', title: '30-Year Fixed Rate Conforming Mortgage Index: Loan-to-Value Greater Than 80, FICO Score Between 700 and 719' },
  { id: 'TGCR1STPERCENTILE', title: 'Tri-Party General Collateral Rate: 1st Percentile' },
  { id: 'RIFSPPNA2P2D30NB', title: '30-Day A2/P2 Nonfinancial Commercial Paper Interest Rate' },
  { id: 'OBMMIC30YFNA', title: '30-Year Fixed Rate Conforming Non-Adjusted Mortgage Index' },
  { id: 'BAMLEM3BRRBBCRPIEY', title: 'ICE BofA BB Emerging Markets Corporate Plus Index Effective Yield' },
  { id: 'RIFSPPAAAD01NB', title: 'Overnight AA Asset-Backed Commercial Paper Interest Rate' },
  { id: 'EFFR1', title: 'Effective Federal Funds Rate: 1st Percentile' },
  { id: 'DFF', title: 'Federal Funds Effective Rate' },
  { id: 'EFFR', title: 'Effective Federal Funds Rate' },
  { id: 'RIFSPFFNB', title: 'Federal Funds Effective Rate' },
];
